blank_issues_enabled: false
contact_links:
    - name: ğŸ› Bug report
      url: https://protonmail.com/support/
      about: Please contact our customer support
    - name: ğŸ’¡ Feature request
      url: https://protonmail.uservoice.com/forums/284483-protonmail
      about: Please submit your feature requests to uservoice
    - name: Bug bounty
      url: https://protonmail.com/blog/protonmail-bug-bounty-program/
      about: Participate in our bug bounty program
