version: "3.7"

services:
  web:
    image: gcr.io/proton-dev-ops/web/calendar/proton-calendar:branch-develop
    environment:
      # Feel free to change any of these values on your local .env file
      API_ENDPOINT:
      MAIL_ENDPOINT:
      CONTACTS_ENDPOINT:
      SETTINGS_ENDPOINT:
    ports:
      - 80:80
      - 443:443
